apiVersion: skaffold/v2beta3
kind: Config
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: pravash27/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.js'
          dest: .
  - image: pravash27/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: pravash27/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: pravash27/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: pravash27/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: pravash27/comment-moderator
    context: comment-moderator
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .